# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/yzi080r2c1zn2jzrhcfdv7dmr92yw07l-cmake-3.29.6/bin/cmake

# The command to remove a file.
RM = /nix/store/yzi080r2c1zn2jzrhcfdv7dmr92yw07l-cmake-3.29.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ezpz/nextcloud/NextcloudData/DevStuff/cpp/validation-api

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ezpz/nextcloud/NextcloudData/DevStuff/cpp/validation-api

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/yzi080r2c1zn2jzrhcfdv7dmr92yw07l-cmake-3.29.6/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/yzi080r2c1zn2jzrhcfdv7dmr92yw07l-cmake-3.29.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ezpz/nextcloud/NextcloudData/DevStuff/cpp/validation-api/CMakeFiles /home/ezpz/nextcloud/NextcloudData/DevStuff/cpp/validation-api//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ezpz/nextcloud/NextcloudData/DevStuff/cpp/validation-api/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named validation-api

# Build rule for target.
validation-api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 validation-api
.PHONY : validation-api

# fast build rule for target.
validation-api/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/build
.PHONY : validation-api/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

src/ConfigService.o: src/ConfigService.cpp.o
.PHONY : src/ConfigService.o

# target to build an object file
src/ConfigService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/ConfigService.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/ConfigService.cpp.o
.PHONY : src/ConfigService.cpp.o

src/ConfigService.i: src/ConfigService.cpp.i
.PHONY : src/ConfigService.i

# target to preprocess a source file
src/ConfigService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/ConfigService.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/ConfigService.cpp.i
.PHONY : src/ConfigService.cpp.i

src/ConfigService.s: src/ConfigService.cpp.s
.PHONY : src/ConfigService.s

# target to generate assembly for a file
src/ConfigService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/ConfigService.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/ConfigService.cpp.s
.PHONY : src/ConfigService.cpp.s

src/ConfigWatcher.o: src/ConfigWatcher.cpp.o
.PHONY : src/ConfigWatcher.o

# target to build an object file
src/ConfigWatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/ConfigWatcher.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/ConfigWatcher.cpp.o
.PHONY : src/ConfigWatcher.cpp.o

src/ConfigWatcher.i: src/ConfigWatcher.cpp.i
.PHONY : src/ConfigWatcher.i

# target to preprocess a source file
src/ConfigWatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/ConfigWatcher.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/ConfigWatcher.cpp.i
.PHONY : src/ConfigWatcher.cpp.i

src/ConfigWatcher.s: src/ConfigWatcher.cpp.s
.PHONY : src/ConfigWatcher.s

# target to generate assembly for a file
src/ConfigWatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/ConfigWatcher.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/ConfigWatcher.cpp.s
.PHONY : src/ConfigWatcher.cpp.s

src/Logger.o: src/Logger.cpp.o
.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/Logger.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i
.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/Logger.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s
.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/Logger.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/lib/Helpers.o: src/lib/Helpers.cpp.o
.PHONY : src/lib/Helpers.o

# target to build an object file
src/lib/Helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/lib/Helpers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/lib/Helpers.cpp.o
.PHONY : src/lib/Helpers.cpp.o

src/lib/Helpers.i: src/lib/Helpers.cpp.i
.PHONY : src/lib/Helpers.i

# target to preprocess a source file
src/lib/Helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/lib/Helpers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/lib/Helpers.cpp.i
.PHONY : src/lib/Helpers.cpp.i

src/lib/Helpers.s: src/lib/Helpers.cpp.s
.PHONY : src/lib/Helpers.s

# target to generate assembly for a file
src/lib/Helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/lib/Helpers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/src/lib/Helpers.cpp.s
.PHONY : src/lib/Helpers.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/validation-api.dir/build.make CMakeFiles/validation-api.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/ConfigServiceTest.o: tests/ConfigServiceTest.cpp.o
.PHONY : tests/ConfigServiceTest.o

# target to build an object file
tests/ConfigServiceTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/ConfigServiceTest.cpp.o
.PHONY : tests/ConfigServiceTest.cpp.o

tests/ConfigServiceTest.i: tests/ConfigServiceTest.cpp.i
.PHONY : tests/ConfigServiceTest.i

# target to preprocess a source file
tests/ConfigServiceTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/ConfigServiceTest.cpp.i
.PHONY : tests/ConfigServiceTest.cpp.i

tests/ConfigServiceTest.s: tests/ConfigServiceTest.cpp.s
.PHONY : tests/ConfigServiceTest.s

# target to generate assembly for a file
tests/ConfigServiceTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/ConfigServiceTest.cpp.s
.PHONY : tests/ConfigServiceTest.cpp.s

tests/ConfigWatcherTest.o: tests/ConfigWatcherTest.cpp.o
.PHONY : tests/ConfigWatcherTest.o

# target to build an object file
tests/ConfigWatcherTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/ConfigWatcherTest.cpp.o
.PHONY : tests/ConfigWatcherTest.cpp.o

tests/ConfigWatcherTest.i: tests/ConfigWatcherTest.cpp.i
.PHONY : tests/ConfigWatcherTest.i

# target to preprocess a source file
tests/ConfigWatcherTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/ConfigWatcherTest.cpp.i
.PHONY : tests/ConfigWatcherTest.cpp.i

tests/ConfigWatcherTest.s: tests/ConfigWatcherTest.cpp.s
.PHONY : tests/ConfigWatcherTest.s

# target to generate assembly for a file
tests/ConfigWatcherTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/ConfigWatcherTest.cpp.s
.PHONY : tests/ConfigWatcherTest.cpp.s

tests/LoggerTest.o: tests/LoggerTest.cpp.o
.PHONY : tests/LoggerTest.o

# target to build an object file
tests/LoggerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/LoggerTest.cpp.o
.PHONY : tests/LoggerTest.cpp.o

tests/LoggerTest.i: tests/LoggerTest.cpp.i
.PHONY : tests/LoggerTest.i

# target to preprocess a source file
tests/LoggerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/LoggerTest.cpp.i
.PHONY : tests/LoggerTest.cpp.i

tests/LoggerTest.s: tests/LoggerTest.cpp.s
.PHONY : tests/LoggerTest.s

# target to generate assembly for a file
tests/LoggerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests/LoggerTest.cpp.s
.PHONY : tests/LoggerTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tests"
	@echo "... validation-api"
	@echo "... src/ConfigService.o"
	@echo "... src/ConfigService.i"
	@echo "... src/ConfigService.s"
	@echo "... src/ConfigWatcher.o"
	@echo "... src/ConfigWatcher.i"
	@echo "... src/ConfigWatcher.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/lib/Helpers.o"
	@echo "... src/lib/Helpers.i"
	@echo "... src/lib/Helpers.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/ConfigServiceTest.o"
	@echo "... tests/ConfigServiceTest.i"
	@echo "... tests/ConfigServiceTest.s"
	@echo "... tests/ConfigWatcherTest.o"
	@echo "... tests/ConfigWatcherTest.i"
	@echo "... tests/ConfigWatcherTest.s"
	@echo "... tests/LoggerTest.o"
	@echo "... tests/LoggerTest.i"
	@echo "... tests/LoggerTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

